[package]
name = "thaf"
version = "0.0.2"
edition = "2024"
authors = ["Bourumir Wyngs <bourumir.wyngs [at] gmail.com>"]
description = "Extracts transcript sequences and gene maps from genome FASTA files using GFF3 annotations."
keywords = ["bioinformatics", "gff3", "transcriptome", "genome", "FASTA"]
categories = ["science", "science::bioinformatics", "science::bioinformatics::genomics", "command-line-utilities"]

license = "BSD-3-Clause"
repository = "https://github.com/bourumir-wyngs/thaf"
readme = "README.md"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
bio = "2.3"
log = "0.4.27"

[dev-dependencies]
tempfile = "3"
